### ISSUE TITLE
[Feature Proposal] Add Decorators

### ISSUE THREAD

**Issue by prowwid** [yiisoft/di#10]
Through container, we can set any default values, attach behaviors, event handlers etc. 

But if there is a bootstrap code that used in different container definitions, add behavior or state to individual objects at run-time or if you want to apply several transformations to an object returned from the container, you need to add a lot of additional code with a meaning that won't be clean to understand sometimes and that won't be really handy.

**I suggest adding support for [decorators](https://sourcemaking.com/design_patterns/decorator) in the container.** 

**Specification**

Each decorator has a method `decorate`  with one argument - object that should be decorated. No other methods are required, so the interface looks like:
```php
/**
 * Represents decorator of any objects.
 *
 * @see https://sourcemaking.com/design_patterns/decorator
 */
interface ObjectDecorator {
    public function decorate($object);
}
```

<hr/>

Decorator can be assigned to a class by its name or identifier in the container, using  method `addDecorator` of the container:
```
$container->addDecorator(Calculator::class, EngineeringDecorator::class);
$container->addDecorator(Calculator::class, ScienceDecorator::class);
```
or through configuration:
```php
'container' => [
    'decorators' => [
        Calculator::class =>  [
            EngineeringDecorator::class,
            ScienceDecorator::class,
        ]
    ]
]
```

<hr/>

Each decorator is a singleton and should be created only one time when a target object is requested from the container.

**Comment by samdark** [comment]
Why should we have decorators separate from other dependencies?

**Comment by prowwid** [comment]
Hello @samdark ,

Sorry, didn't get what you are asking. Could you please explain with more details?

I would expand the idea with better examples and description a bit later today.

With best regards,
Dmitry

**Comment by samdark** [comment]
I don't see how decorator itself matches the concept of DI container i.e. you can store decorator into container but I see no reason why this case should be special. Same as storing non-decorated object, you're setting an object using a named key and it doesn't matter which type of object it is.

**Comment by prowwid** [comment]
@samdark thank you for cleaning things up

**First of all, let's talk about Decorators and how they can be used in Yii.** 

A typical Decorator can look like:
```php
class Book {
    private $author;
    private $title;

    public function __construct($title, $author) {
        $this->author = $author;
        $this->title  = $title;
    }

    public function getAuthor() {
        return $this->author;
    }

    public function getTitle() {
        return $this->title;
    }
    public function getAuthorAndTitle() {
      return $this->getTitle() . ' by ' . $this->getAuthor();
    }
}

class BookTitleStarDecorator {
    protected $book;
    protected $title;

    public function __construct(Book $book) {
        $this->book = $book;
        $this->resetTitle();
    }   

    //doing this so original object is not altered
    public function resetTitle() {
        $this->title = $this->book->getTitle();
    }

    public function showTitle() {
        return $this->title;
    }

    public function starTitle() {
        $this->title = str_replace(" ", "*", $this->title);
    }
}
```

And can be used like:
```php
$patternBook = new Book('Gamma, Helm, Johnson, and Vlissides', 'Design Patterns');
$starDecorator = new BookTitleStarDecorator($patternBook);

echo $starDecorator->showTitle();
```
Example based on [this sources](https://sourcemaking.com/design_patterns/decorator/php)

_But in Yii we can use Behaviors to achieve the same result._ 

So having something like:
```php
use yii\base\Behavior;
use yii\base\Component;

class Book extends Component {
    private $author;
    private $title;

    public function __construct($title, $author) {
        $this->author = $author;
        $this->title = $title;
    }

    public function behaviors() {
        return [
            'startDecorator' => BookTitleStarDecorator::class,
        ];
    }

    public function getAuthor() {
        return $this->author;
    }

    public function getTitle() {
        return $this->title;
    }
    
    public function getAuthorAndTitle() {
        return $this->getTitle() . ' by ' . $this->getAuthor();
    }
}

/**
 * @property Book $owner
 */
class BookTitleStarDecorator extends Behavior {
    protected $book;
    protected $title;

    public function attach($owner) {
        parent::attach($owner);
        $this->resetTitle();
    }

    //doing this so original object is not altered
    public function resetTitle() {
        $this->title = $this->book->getTitle();
    }

    public function showTitle() {
        return $this->title;
    }

    public function starTitle() {
        $this->title = str_replace(" ", "*", $this->title);
    }
}
```
We can achieve the same result even with less code:
```php
$patternBook = new Book('Gamma, Helm, Johnson, and Vlissides', 'Design Patterns');

echo $patternBook->showTitle();
```

Yet, in situations when the same method behavior should be extended in several decorators, using Yii Behaviors would be a bit trickier than using an explicit decorator, like in the first example.

I would dare to say, most of the time Decorator pattern can be implemented through Yii Behavior.  
But defining Decorators through Behaviors all the time might not be an option.

For example, imagine that you have a model(let's say User) that is used in 7 modules of the application. Each module requires decorator specific to the module attached to the model and there are 2 common decorators that being used in almost all of the modules. 
So we have 9 behaviors attached to the model in the end and only 3 required during execution in a module (2 common and 1 specific to a module).
Typically to prevent the model from overloading with redundant behaviors we would need to have factories  that attach required behavior to the model in each of the module (or something like this) to prevent listing all of the behaviors in the model.

**So how container can help us?**

With the ability to set behavior on a module level we can both include performance and reduce redundant code in the model.
And in the end, having common behaviors in the model:
```php
class User extends Model {
    public function behaviors() {
        return [
            'activity' => ActivityBehavior::class,
            'status' => StatusBehavior:::class,
        ];
    }
}
``` 
and specific to the module initialized only per module, like:
```php
// in first module
$container->addDecorator(User::class, BehaivorDecorator::for(PaymentBehavior::class));

// in second module
$container->addDecorator(User::class, BehaivorDecorator::for(StatisticBehavior::class));

// and so on
``` 
Behaviors are only the first thing came to my mind, but container decorator can do pretty much everything with an object.

**And now to your question:**

> I don't see how decorator itself matches the concept of DI container i.e. you can store decorator into container but I see no reason why this case should be special
First of all, let's talk about container itself. 

Container implements of the [Inversion Of Control Principle](https://en.wikipedia.org/wiki/Inversion_of_control) using [Dependency Injection](https://en.wikipedia.org/wiki/Dependency_injection) technic which allows us to achieve [Dependency Inversion](https://en.wikipedia.org/wiki/Dependency_inversion_principle) in software we build.

And when using IoC container you should follow simple rules, few of them are:
- do not use container directly outside of bootstrap areas
- do not create objects using `new` operator (of course this rule is not for all of the possible cases as there are situations when you are allowed to use `new`, like when you create value object) 
So, basically, you should not have such code:
```php
$patternBook = new Book('Gamma, Helm, Johnson, and Vlissides', 'Design Patterns');
$starDecorator = new BookTitleStarDecorator($patternBook);

echo $starDecorator->showTitle();
```
Container responsible for dealing with this situation.
 
This is why Symfony IoC Container (one of the best available for PHP) have decorators. 
You can read about [Symfony Service Decorating](https://symfony.com/doc/current/service_container/service_decoration.html). 

But I would show Container configuration  for book decorator could look like:
```yaml
book:
    class: Book

book_decorator:
    class: BookStarDecorator
    public: false
    decorates: book
```

Yet Symfony's container would have something like `new BookStarDecorator(new Book(...$params))`in the end as their decorator being implemented using explicit classes. And you'll receive BookStarDecorator except of Book in the code (which might not be good im many cases)

But what I suggest is to have Container Decorators that would decorate  classes without replacing them, like:
```php

class BehaviorDecorator {
    public function decorate($book) {
        $book->attach(StarBehavior::class);
    }
}

class QuotedTitleDecorator {
    public function decorate($book) {
        $book->title = " '{$book->title}' ";
    }
}
``` 

Looking forward to your comments.

**Comment by samdark** [comment]
I think it could be easily achieved with current features:

```php
class MyObject implements MyInterface
{
}

class MyDecorator
{
    // doesn't matter how we decorate objects, constructor or method
    public function __construct(MyInterface $object) {}

    public function newMethod() {}
}

$container->set('original_serivce', MyInterface::class);
$container->set('decorated_service', [
    '__class' => MyDecorator::class,
   '__construct' => [new Reference('original_service')],
]);
```

**Comment by prowwid** [comment]
Hello @samdark 

If we would need two (or more) different services, then yes,  your current abilities of the container would cover such case.

But I'm talking about a case when we have only one realization. For example:
```php
$container->set(CalculatorInterface::class, Calculator::class);

$container->addDecorator(CalculatorInterface::class, ScienceDecorator::class);
$container->addDecorator(CalculatorInterface::class, EngineeringDecorator::class);

$container->get(CalculatorInterface::class); // RETURNS Calculator decorated by ScienceDecorator and EngineeringDecorator 
```
we have only one calculator and every time `CalculatorInterface` is requested we would have `Calculator` decorated by all of the decorators we need.

Looking forward to your comments.

**Comment by samdark** [comment]
```php
$container->set('calculator', Calculator::class);
$container->set('science_calculator', [
    '__class' => ScienceDecorator::class,
   '__construct' => [new Reference('calculator')],
]);
$container->set('science_and_engineering_calculator', [
    '__class' => EngineeringDecorator::class,
   '__construct' => [new Reference('calculator')],
]);
$container->alias(CalculatorInterface::class, 'science_and_engineering_calculator');
```

**Comment by prowwid** [comment]
Hello @samdark,

again, in your example 
```php
$container->get(CalculatorInterface::class);
```
would result in
```php
new EngineeringDecorator(
    new ScienceDecorator(
        new Calculator()
    )
);
```

which would require creating two(in this example of course - in real life we can have more) additional classes that had to implement all of the methods of `CalculatorInterface`.

What I'm talking about is something like:
```php
// decorator function
function addScienceFeatures(Calculator $calculatorToDecorate){
    $calculatorToDecorate->attach(ScienceFeatures::class);
};

// decorator function
function addEngineeringFeatures(Calculator $calculatorToDecorate){
    $calculatorToDecorate->attach(ScienceFeatures::class);
};

$calculator = new Calculator();

addScienceFeatures($calculator);
addEngineeringFeatures($calculator);
``` 

This feature proposal is all about having the ability to decorate object at runtime without the need of creating additional classes that implement an interface of the target class and having an easy way to create generic decorators you can use with any object (for example, bootstrap of default values).

**Comment by samdark** [comment]
@prowwid I've basically posted what you're originally did. You've hinted decorated object with `CalculatorInterface::class` same as I did.

**Comment by samdark** [comment]
I'm a bit lost. Are we talking about decorators or about behaviors?

**Comment by prowwid** [comment]
Hello @samdark 

Sorry if I made you lost. Let me explain again in other words. 

Let's forget about calculator, interfaces, and behaviors.
Imagine that we have `Book` and `Author` models:
```php
class Book extends Model {
    public $title;
    public $rating;
    public $author;
}

class Author extends Model {
    public $name;
}
```
And have two modules where it would be displayed: `search` and `listing`.
In search we want `book` title to be upper-cased but in the listing, we want book title and author to be upper-cased and rating to be displayed as stars. 
`Author` model will be used in `search` without changes and only in the `listing` module with an upper-cased name.

To achieve this, we can have following decorators:
```php

class AttributeCapitalizeDecorator {
    public $attribute;
    public function decorate($model) {
        strtoupper($model->{$this->attribute});
    }
}

class NumberToStarDecorator {
    public $attribute;

    public function decorate($model) {
        $rating = $model->{$this->attribute};
        if ($rating > 1) {
            $stars = str_pad('', $rating, '*');
        } else {
            $stars = '*';
        }
        $model->{$this->attribute} = $stars;
    }
}
```

and use decorators directly in controller actions(without container):
```php
// ------------------- IN SEARCH MODULE -------------------- 
// action code
$capitalizeDecorator = new AttributeCapitalizeDecorator();
$capitalizeDecorator->attribute = 'title';

$capitalizeDecorator->decorate($book)
// view code
```
```php
// ------------------- IN LISTING MODULE -------------------- 
// action code
$capitalizeDecorator = new AttributeCapitalizeDecorator();
$capitalizeDecorator->attribute = 'title';
$capitalizeDecorator->decorate($book)

$capitalizeDecorator->attribute = 'author';
$capitalizeDecorator->decorate($book)

$starDecorator  = new  NumberToStarDecorator();
$starDecorator->attribute = 'rating';

$starDecorator->decorate($book);

$capitalizeDecorator->attribute = 'name';
$capitalizeDecorator->decorate($author)
// view code
```

Even with two decorators, it's a lot of redundant code in actions and more decorators would be needed - more redundant code added. 

**But with the container, we can simplify everything to a simple configuration on app and module bootstrap.** 
So, in main app configuration we can have something like:
```php
[
    'container' => [
        'decorators' => [
            Book::class => [
                [
                    '__class' => AttributeCapitalizeDecorator::class,
                    'attribute' => 'title',
                ]
            ]
        ]
    ]
]
```
than, only in listing module, at bootstrap(init) stage:
```php
$container->addDecorator(Book::class, [
    '__class' => AttributeCapitalizeDecorator::class,
    'attribute' => 'author',
]);

$container->addDecorator(NumberToStarDecorator::class, [
    '__class' => AttributeCapitalizeDecorator::class,
    'attribute' => 'rating',
]);

$container->addDecorator(Author::class, [
    '__class' => AttributeCapitalizeDecorator::class,
    'attribute' => 'name',
]);
```
**P.S.** let's not discuss that this example could be implemented without decorators or optimized with better approaches - the goal of example only to show how decoarators could be used with container.

**And back to behaviors.**  
I've mentioned them because they would be probably the first thing to use inside decorator to apply new behavior to an object, like:
```php
class TimeStampDecorator {
    public function decorate($model) {
        $model->attach(TimeStampBehavior::class);
    }
}
```

**And the calculator**. 
Examples of decorators that work like:
```php
new EngineeringDecorator(
    new ScienceDecorator(
        new Calculator()
    )
);
```
was to show how people typically do decoration and how it is implemented in Symfony but I'm not suggesting to implement decorators this way.

I suggest having decorators like functions(callable classes) called over an object - something like [Python decorators](https://www.thecodeship.com/patterns/guide-to-python-function-decorators/) (or [TypeScript decorators](http://www.typescriptlang.org/docs/handbook/decorators.html))

Hope I've cleaned things a bit.

Looking forward to your comments.

**Comment by samdark** [comment]
Yes, it's clear now. I have concerns though:

1. If we'll implement it this way we'll need a specific interface for decorators (`decorate()` method) thus won't be able to reuse any existing decorators. In reality, decorator is a general pattern. Implementation may have multiple methods (toggling decoration on and off, multiple alike methods to decorate a bit differently etc.).
2. Config is becoming scattered into multiple sections. There's no indication in the service definition itself that any decorators are applied (you have to check decorators section all the time).

**Comment by prowwid** [comment]
@samdark , 

**As for №1**
This is why I've talked about behaviors. It's a common approach in Yii community to attach behaviors to an object to add new functionality (new methods or properties) or change the behavior of an object through events.  So I would say that actual implementation of a Decorator Pattern in Yii community would be based on behaviors. And with an ability to attach behaviors at run-time through the container (decorate object) decorating objects through behaviors would be much easier.

And decorator pattern implementation through classes that receive target object through constructor could be achieved through aliasing features of the container (as you said before). 
Yet such kind of decorator implementation is almost the same as the implementation of Proxy(which is also useful) and can be implemented as a separate feature to support Proxy pattern.

But for the current proposal, I believe it would be enough having the support of decorators with the following interface:
```php
interface ObjectDecorator {
    public function decorate($object);
}
```
and callables, for simple decorators like:
```php
function initDate(DateAware $obj) {
    $obj->date = new \DateTime();
}
```


**As for №2**
Well, it's the downside of using container - you should always know where a class is defined and configured. I believe it's more like a team organization question.
If a team isn't experienced in following IoC principles, using container and following conventions over configuration, then, probably,  even having the ability to set decorators in a class definition (I don't think for a case with definition as a callable it would be handy) won't be really helpful .

**Comment by samdark** [comment]
Behaviors could be attached via regular object config. This container isn't meant to be Yii-specific so I'd prefer not to add Yii-specific features.

**Comment by prowwid** [comment]
Hello @samdark ,

to reduce the talk, I've prepared basic implementation in this [PR](https://github.com/yiisoft/di/pull/12)
could you please take a look?

**Comment by samdark** [comment]
I will.

**Comment by prowwid** [comment]
Closing this issue as implementation not going to be accepted.
