### ISSUE TITLE
Incorrect work of FactoryProvider->has()

### ISSUE THREAD

**Issue by roxblnfk** [yiisoft/di#104]
README.MD: # Using deferred service providers [[link](https://github.com/yiisoft/di#using-deferred-service-providers)]

> ```php
> // returns false as provider wasn't registered
> $container->has(EngineInterface::class); 
> 
> // returns SolarEngine, registered in the provider
> $engine = $container->get(EngineInterface::class); 
> 
> // returns true as provider was registered when EngineInterface was requested from the container
> $container->has(EngineInterface::class); 
> ```

PSR about `has()`:
> [1.1.2 Reading from a container](https://www.php-fig.org/psr/psr-11/#112-reading-from-a-container)
> has takes one unique parameter: an entry identifier, which MUST be a string. has MUST return true if an entry identifier is known to the container and false if it is not. If has($id) returns false, get($id) MUST throw a NotFoundExceptionInterface.

> [3.1. Psr\Container\ContainerInterface](https://www.php-fig.org/psr/psr-11/#31-psrcontainercontainerinterface)
> ```php
>     /**
>      * Returns true if the container can return an entry for the given identifier.
>      * Returns false otherwise.
>      *
>      * `has($id)` returning true does not mean that `get($id)` will not throw an exception.
>      * It does however mean that `get($id)` will not throw a `NotFoundExceptionInterface`.
>      *
>      * @param string $id Identifier of the entry to look for.
>      *
>      * @return bool
>      */
>     public function has($id);
> ```

Method `get()` must returns `true` if the container can return an entry for the given identifier. 
In our case, it returns `false` until the first call to `get()`

**Comment by samdark** [comment]
Need to cover it with unit test...
