### ISSUE TITLE
Remove second parameter from get()

### ISSUE THREAD

**Issue by viktorprogger** [yiisoft/di#106]
This parameter is used only with the very first call of the `get` method. You can pass different parameters for a single dependency as many times as you want, but they would be used just once because all the dependencies in the container are singletons. Ability to use this argument disorientates and leads to errors.

**Comment by samdark** [comment]
https://github.com/yiisoft/di/pull/105/files#diff-00897e77b93946555bcac5b95e73e3a9R22

**Comment by samdark** [comment]
Done in https://github.com/yiisoft/di/commit/736926c8d498b77d8a148c49b19c8e8f8d59f9aa
