### ISSUE TITLE
CompositeContainer is not working

### ISSUE THREAD

**Issue by xepozz** [yiisoft/di#107]
### What steps will reproduce the problem?
1. Run the following code:
```php
$container = new \Yiisoft\Di\CompositeContainer();
$container1 = new Container([
    'first' => function () {
        return 'first';
    }
]);
$container2 = new Container([
    'second' => function () {
        return  'second';
    },
    'third' => function ($c) {
        return $c->get('first') . $c->get('second') . 'third';
    },
]);

$container->attach($container1);
$container->attach($container2);
var_dump($container->get('first')); // works
var_dump($container->get('second')); // works
var_dump($container->get('third')); // not working :C
```

### What is the expected result?
Each `$container->get()` should return result
```
string(5) "first" string(6) "second" string(16) "firstsecondthird"
```
### What do you get instead?
```
string(5) "first" string(6) "second"
Fatal error: Uncaught Yiisoft\Factory\Exceptions\CircularReferenceException: Circular reference to "first" detected while building: first,third in /app/vendor/yiisoft/di/src/Container.php:105 Stack trace: #0 /app/vendor/yiisoft/di/src/Container.php(80): Yiisoft\Di\Container->build('first', Array) #1 /app/public/index.php(18): Yiisoft\Di\Container->get('first') #2 /app/vendor/yiisoft/factory/src/Definitions/CallableDefinition.php(19): {closure}(Object(Yiisoft\Di\Container), Array) #3 /app/vendor/yiisoft/di/src/Container.php(134): Yiisoft\Factory\Definitions\CallableDefinition->resolve(Object(Yiisoft\Di\Container), Array) #4 /app/vendor/yiisoft/di/src/Container.php(114): Yiisoft\Di\Container->buildInternal('third', Array) #5 /app/vendor/yiisoft/di/src/Container.php(80): Yiisoft\Di\Container->build('third', Array) #6 /app/vendor/yiisoft/di/src/CompositeContainer.php(25): Yiisoft\Di\Container->get('third') #7 /app/public/index.php(25): Yiisoft\Di\CompositeContainer->get('third') #8 {main} thrown in /app/vendor/yiisoft/di/src/Container.php on line 105
```

Any idea how to solve this?

-------

### UPD:
If try to do `$container->get('third')` only, then we get:
```
Fatal error: Uncaught Yiisoft\Factory\Exceptions\NotFoundException: No definition for third in /app/vendor/yiisoft/di/src/CompositeContainer.php:30 Stack trace: #0 /app/public/index.php(25): Yiisoft\Di\CompositeContainer->get('third') #1 {main} thrown in /app/vendor/yiisoft/di/src/CompositeContainer.php on line 30
```
It happends because `thrid` is not found in the first container. In the second container `third` is found,  but `first` is not found.

**Comment by samdark** [comment]
What happens if we won't execute the following?

```php
var_dump($container->get('first')); // works
var_dump($container->get('second')); // works
```

**Comment by samdark** [comment]
It breaks as well.

**Comment by xepozz** [comment]
The usecase for CompositeContainer:

- We have 2 containers in modules moduleA and moduleB, 1 composite container and 1 regular container from main app.
  Ultimately we have 1 aggregate container, that managed with 3 regular containers.
- Regular container have definitions for all PSR interfaces: EventDispatcher, Cache, Http and etc.
- Containers from moduleA and moduleB depends on PSR interfaces and don't configure any implementation.

**Comment by viktorprogger** [comment]
And what are the reasons for `moduleA` to provide an instantiated container?

**Comment by viktorprogger** [comment]
IMHO external modules must not create container instances. And for modules of a single project we can implement smthng lilke [Symfony did](https://symfony.com/doc/2.4/components/dependency_injection/parentservices.html).

**Comment by viktorprogger** [comment]
E.g. we can implement a class like this:

```php
class NestedContainer
{
    private $definitions;
    private $parentContainer;

    public function __construct($definitions, $container)
    {
        $this->definitions = $definitions;
        $this->parentContainer = $container;
    }

    protected function get($id)
    {
        $dependency = $this->getAsAlways($id);

        if ($dependency === null) {
            $dependency = $this->parentContainer->get($id);
        }
    }
}
```

**Comment by xepozz** [comment]
> E.g. we can implement a class like this:
> 
> ```
> class NestedContainer
> ```

It looks like `CompositeContainer` :)

**Comment by viktorprogger** [comment]
> It looks like CompositeContainer :)
`CompositeContainer` can get dependencies from the given containers, but it can't control how do these containers resolve dependencies. I'm talking about container that knows it is nested. As an idea, we can do this for the default container.

**Comment by xepozz** [comment]
Yes, we need this feature.
I think it may be developed as [like this](https://github.com/yiisoft/di/pull/108) but much smarter.
General idea: the container firstly receives all the dependencies from itself, and if not then from the main container

**Comment by viktorprogger** [comment]
> General idea: the container firstly receives all the dependencies from itself, and if not then from the main container

I'd prefer to say "from its parent".

**Comment by xepozz** [comment]
The main container must be not parent only

**Comment by viktorprogger** [comment]
When I'm trying to get dependency from the third nesting level and can't find one of its dependencies there, I must to check it in the second level because second level container may override dependency definition specially for itself and its children.

**Comment by xepozz** [comment]
Yes you are right. In this case, you can recursively go up and check all the containers

**Comment by viktorprogger** [comment]
> I think it may be developed as [like this](#108) but much smarter.

Tryed to improve [your PR](#108) and got the problem: if a container has no a dependency for a service, then composite container **must** add this definition to that container and try to `get` the service again. There is no other way.

So my desicion is to add `ContainerInterface` as a parameter to the `Container` constructor and to try to find dependencies inside it when they are not found in the current container.

**Comment by viktorprogger** [comment]
And one more minus to this idea: it will work slowly.

**Comment by xepozz** [comment]
Yes, but we can solve it later :)

**Comment by samdark** [comment]
That's due to #80. The support was there but was removed. #116 is going to re-add it.
