### ISSUE TITLE
Feature: decorators

### ISSUE THREAD

**Issue by xepozz** [yiisoft/di#110]
Would be nice allow to decorate already existing services in container.
I see at least 2 variants of usage:
1. Decorating already existing service that exist in another container (applied only to `CompositeContainer`)
  // config/common.php
  ```php
  return [
    // ...
    LoggerInterface::class => function() use ($compositeContainer) {
      return new LoggerDecorator($compositeContainer->get(LoggerInterface::class));
    }
    // ...
  ];
  ```
  At now it parsed as `circle dependency`, but we can modernize this syntax. At now it doesn't matter.
2. Decorating already existing services in current container
  // config/common.php
  ```php
  return [
    // ...
    LoggerInterface::class => /* ... */,
    
    LoggerDecorator::class => [
        'decorated' => LoggerInterface::class
    ];
    // ...
  ];
  ```
  or
// config/common.php
  ```php
  return [
    // ...
    LoggerInterface::class => /* ... */,
    // ...
  ];
  ```
  // config/common.dev.php
  ```php
  return [
    // ...
    LoggerInterface::class => function ($container) {
        return new LoggerDecorator($container->get(LoggerInterface::class));
    }
    // ...
  ];
  ```
   
### What is the expected result?
In all cases `$container->get(LoggerInterface::class)` should return `LoggerDecorator`

### What do you get instead?
In the first case we have `CircularReferenceException`. In the second case we have `LoggerInterface` implementation that passed via `/* ... */ or `CircularReferenceException`.

### Additional info
I think we need to think all future features for another cases (I'm not about decorators only).

**Comment by xepozz** [comment]
I made syntax examples. 

```php
LoggerInterface::class => (new ContainerBuilder())
  ->callback(fn () => new Logger())
  ->decorate(fn ($container, $logger) => new LoggerDecorator($logger));
```

```php
LoggerInterface::class => (new ContainerBuilder())
  ->callback(fn () => new Logger())
  ->decorate(LoggerDecorator::class),
LoggerDecorator::class => fn ($container) => new LoggerDecorator($container->get(LoggerInterface::class)),
```

```php
$definitions = [
  LoggerInterface::class => fn () => new Logger(),
  LoggerDecorator::class => fn ($container) => new LoggerDecorator($container->get(LoggerInterface::class)),
];
$containerBuilder
  ->decorate(LoggerInterface::class, LoggerDecorator::class)
  ->decorate(ContainerInterface::class, ContainerDecorator::class);
```

**Comment by viktorprogger** [comment]
#10

**Comment by viktorprogger** [comment]
Why does decorators are better than nested/contextual containers?

**Comment by xepozz** [comment]
Using decorators we can to substitude any dependencies from PSR container, not only Yii container.
It looks more cleaner and flexible.
Nested container is a part of way to use decorators.

Do you have examples with contextual container that solve this problem?
