### ISSUE TITLE
Feature: caching

### ISSUE THREAD

**Issue by viktorprogger** [yiisoft/di#111]
We can introduce dependecy caching in order to make container faster. I'd like to see a decision that will result into some php files with methods like these:

```php
public function getSomeDependency(ContainerInterface $container)
{
    return new SomeDependency($container->get('anotherDependency'));
}

public function getAnotherDependency(ContainerInterface $container)
{
    return new AnotherDependency();
}
```

**Comment by samdark** [comment]
That's good and bad at the same time. Good because yes, likely it would be more performant. Bad because you're executing not what you've actually written so debugging becomes quite weird experience.

**Comment by armpogart** [comment]
Maybe it's better to have a way to generate compiled container for production use-case and document it the way [PHP-DI](http://php-di.org/doc/performances.html#compiling-the-container) and [Symfony](https://symfony.com/doc/current/components/dependency_injection/compilation.html) do it.

**Comment by samdark** [comment]
@armpogart as I've mentioned, it's both good an bad. Need to check if performance gain worth the trouble,

**Comment by viktorprogger** [comment]
Some time passed... For now I think the best way to increase performance in a such way is either RoadRunner/Swoole/etc., or php preloading usage. Everything will be created just once :)

**Comment by samdark** [comment]
Yeah. That's the way to go. I think we can close this issue. Container reset is a separate one.
