### ISSUE TITLE
Ability to reset some definitions

### ISSUE THREAD

**Issue by samdark** [yiisoft/di#121]
## Service types

There are two types of services:

1. Stateless. 
2. Stateful.

In general, services should be stateless but there are some exceptions from the rule. When working in traditional environment, state is not the problem since each request-response happens in separate environment.

When working with [RoadRunner](https://github.com/yiisoft/docs/blob/master/guide/en/tutorial/using-yii-with-roadrunner.md) or [Swoole](https://github.com/yiisoft/docs/blob/master/guide/en/tutorial/using-yii-with-swoole.md), worker is processing multiple requests and we're gaining performance by not doing re-initialization time of the container and framework.

Stateless services are ideal for the purpose. They are initialized once and then re-used. There are no side effects since there's no state involved.

Stateful services, on the other hand, should be reset after each request-response cycle. They could have a dedicated method for the purpose but likely they won't if their author did not consider non-traditional even loop environments.

It would be great to have an ability to specify which services should be reset **when configuring container**.

## Multiple containers

It is not necessary that there is a single container in the application. There could be additional ones provided by packages (modules). We don't have a list of these in runtime.

**Comment by samdark** [comment]
See https://github.com/yiisoft/di/pull/120

**Comment by samdark** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Reset-able container](https://trello.com/c/tpsrVyuZ/28-reset-able-container)

**Comment by samdark** [comment]
@roxblnfk presented an interesting concept that is about introducing a separate package `di-state-reset`.

1. It will contain a single service `StateResetter`.
2. The service accepts an array of callbacks as configuration.
3. via config plugin you're able to register additional callbacks for your packages.
4. When used in RoadRunner or Swoole environment we call `$container->get(StateResetter::class)->reset()`. It executes callbacks one by one using injector to inject dependencies.

**Comment by yiiliveext** [comment]
> @roxblnfk presented an interesting concept that is about introducing a separate package `di-state-reset`.
> 
> 1. It will contain a single service `StateResetter`.
> 2. The service accepts an array of callbacks as configuration.
> 3. via config plugin you're able to register additional callbacks for your packages.
> 4. When used in RoadRunner or Swoole environment we call `$container->get(StateResetter::class)->reset()`. It executes callbacks one by one using injector to inject dependencies.

Maybe it would be interesting. Need an example of the config an callbacks.

**Comment by samdark** [comment]
`config/state-reset.php`

```php
return [
    'yiisoft/my-package1' => function (MyService1 $service) {
        $service->reset();
    },
    'yiisoft/my-package2' => function (MyService2 $service) {
        $service->reset();
    },
];
```

**Comment by yiiliveext** [comment]
> `config/state-reset.php`
> 
> ```
> return [
>     'yiisoft/my-package1' => function (MyService1 $service) {
>         $service->reset();
>     },
>     'yiisoft/my-package2' => function (MyService2 $service) {
>         $service->reset();
>     },
> ];
> ```
