### ISSUE TITLE
[RFC] Tags support

### ISSUE THREAD

**Issue by BoShurik** [yiisoft/di#125]
E.g. I have a telegram bot with commands implementing some `CommandInterface`. And I have  `HelpCommand` which must show all available commands.
Now to achieve this I must edit `HelpCommand` configuration every time I add new command to the bot.
Using tags I can tag command as a `telegram-bot-command` so It will be automatically loaded by `HelpCommand`

Same feature in [Laravel](https://laravel.com/docs/7.x/container#tagging) and [Symfony](https://symfony.com/doc/current/service_container/tags.html#reference-tagged-services)

**Comment by samdark** [comment]
i.e. Container collects all the tagged classes, forms a list and passed the list as an argument of `HelpCommand`.

**Comment by samdark** [comment]
That could be useful but there are possible disadvantages as well: implicitness, unable to know what's passed to `HelpCommand` by looking the config.

**Comment by BoShurik** [comment]
> unable to know what's passed to HelpCommand by looking the config

Catch me if I wrong, but in case non-FQCN service names it's almost the same level of knowledge:
```
return [
    SomeService::class => [
        '__construct()' => [Reference::to('some-dependency')],
    ],
]
```
and
```
return [
    HelpCommand::class => [
        '__construct()' => [Reference::tag('telegram-bot-command)],
    ],
]
```
In the first example you need to find `some-dependency` definition in all sources.

Of course it would be good to have some sort of debug tool. Something like Symfony's
`bin/console debug:container --tag='console.command'`

**Comment by samdark** [comment]
Without tags it will be:

```php
return [
    SomeService::class => [
        '__construct()' => [
            Reference::to(Command1::class),
            Reference::to(Command2::class),
            Reference::to(Command3::class),
        ],
    ],
]
```

**Comment by BoShurik** [comment]
I mean without FQCN services it would be
```
return [
    SomeService::class => [
        '__construct()' => [
            Reference::to('command'),
            Reference::to('other-command'),
            Reference::to('some-other-command'),
        ],
    ],
]
```
So you have to use grep to find class names. Almost the same as with tags

**Comment by samdark** [comment]
We are usually using FQNs.

**Comment by BoShurik** [comment]
Yes, everybody does, but sometimes it's impossible.
Anyway, it's hard to implement described example without tags.
The problem is that developers focusing on creating new commands and can forgot / don't know to add it in `HelpCommand`.

**Comment by samdark** [comment]
Got it. Need to evaluate if it is possible without introducing compiler pass that I want to avoid.

**Comment by samdark** [comment]
https://github.com/illuminate/container/blob/master/Container.php#L476

**Comment by BoShurik** [comment]
It would be good to define tags with service definition, otherwise it's also easy to forget to update tags

**Comment by samdark** [comment]
@BoShurik an example would be helpful.

**Comment by BoShurik** [comment]
In Laravel's container definition of tags is separated from service definition
```php
$this->app->bind('MemoryReport', function () {
    //
});

$this->app->tag(['SpeedReport', 'MemoryReport'], 'reports');
```

In that case it's also easy to forget to tag service.

I would prefer something like this:
```php
return [
    SomeCommand::class => [
        '!tag' => 'telegram-command'
    ],
]
```

**Comment by yiiliveext** [comment]
> I would prefer something like this:
> 
> ```
> return [
>     SomeCommand::class => [
>         '!tag' => 'telegram-command'
>     ],
> ]
> ```

We're using this approach in this or https://github.com/yiisoft/di/pull/120

**Comment by yiiliveext** [comment]
https://github.com/yiisoft/di/pull/144
