### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by samdark** [yiisoft/di#130]

**Comment by mikehaertl** [comment]
@samdark Is the README up-to-date? If so I could fix some typos and grammatical errors and also maybe provide some stylistic improvements. Just le me know how far this should go. I'm not a native english speaker either, but I feel like the gap German <-> English is sometimes a bit narrower than Russian <-> English (definitely when it comes to the use of definite/indefinite articles "**the**" and "**a**" :wink: )

OT 1: I also found that lacking or only cursory documentation also affects many other new packages and that this could be a real hinderance for adoption of Yii 3. If I remember correctly there was some professional technical writer for this in Yii1 / Yii2. Are there any plans here? 

OT 2: Also method comments are often missing or incomplete. From a good framework I would expect that they should be in perfect shape an leave no question open - much like what we had in most parts of yii1 / yii2. But maybe best practices have change here. I even would add more inline comments for complex/not so easy to follow code parts. Core developers come and go over the years and they should have it easy to grasp concepts. Your opinion?

**Comment by samdark** [comment]
> Is the README up-to-date?

README is so-so up-to-date but there are changes planned.

> I feel like the gap German <-> English is sometimes a bit narrower than Russian

You're absolutely right.

> OT 1: I also found that lacking or only cursory documentation also affects many other new packages and that this could be a real hinderance for adoption of Yii 3. If I remember correctly there was some professional technical writer for this in Yii1 / Yii2. Are there any plans here?

You remember it correctly. @larryullman did a great job back then improving Yii 2 docs style. The docs themselves were written mainly by @xwz and @qiangxue.

There were plans to get professional writer on board but these were hindered and postponed by covid.

> OT 2: Also method comments are often missing or incomplete. From a good framework I would expect that they should be in perfect shape an leave no question open - much like what we had in most parts of yii1 / yii2. But maybe best practices have change here. I even would add more inline comments for complex/not so easy to follow code parts. Core developers come and go over the years and they should have it easy to grasp concepts. Your opinion?

We focus on the code for now though and adding more phpdoc closer to first package release to save some time on re-designs. There are some changes such as not using `@inheritdoc`: https://github.com/yiisoft/docs/blob/master/014-docs.md I'd love to keep code documentation quality up to Yii 2 standards.

**Comment by mikehaertl** [comment]
> README is so-so up-to-date but there are changes planned.

Ok, then I maybe better wait.

> There were plans to get professional writer on board 

Great!

> We focus on the code for now though and adding more phpdoc closer to first package release to save some time on re-designs.

Alright. If you want, you can ping me. If I find time I could maybe help with reviewing/completing some comments/docs etc.

**Comment by samdark** [comment]
Thanks!

**Comment by samdark** [comment]
Overall what could be used in container currently:

1. ReferenceInterface  - A link to another service.
2. A string - Service class name. An instance of the class will be created.
3. Callable. Will be executed and should return a service instance.
4. A service object instance.
5. Array for array definition in one of the two formats. See https://github.com/yiisoft/di/issues/213
