### ISSUE TITLE
Check if there's an issue when there are many levels of sub-dependencies

### ISSUE THREAD

**Issue by samdark** [yiisoft/di#132]
Potentially using many levels of sub-dependencies would result in PHP call stack limit error. Need to check that.

**Comment by BoShurik** [comment]
How much "many levels"? I've tried to test this package with https://github.com/kocsismate/php-di-container-benchmarks (100 dependencies) and it works fine

**Comment by samdark** [comment]
Sounds alright. Let's close it then. Thanks for re-checking.
