### ISSUE TITLE
Public API method is protected

### ISSUE THREAD

**Issue by armpogart** [yiisoft/di#138]
`Yiisoft\Di\Container::set` method is `protected` despite the fact that it is used in service providers to set dependencies. I'm not even sure how it works, I've detected the problem while using IDE autocomplete.

I would also appreciate if somebody explained me how it works while being protected and doesn't trigger error.

**Comment by armpogart** [comment]
Hmm... as far as I see it is possible to access `protected` and even `private` properties and methods of the other object as long as they share the same parent (are of the same type) and here `ServiceProvider` and `Container` both extend from `AbstractContainerConfigurator`, but I still think that it is incorrect in terms of strict OOP (though PHP OOP allows it) and we need to make the `set` method public.

Do I need to make a quick PR?

**Comment by samdark** [comment]
> I still think that it is incorrect in terms of strict OOP (though PHP OOP allows it)

It's not. That's the friendly classes concept. Works the same in all OO languages with inheritance such as Java.

**Comment by samdark** [comment]
Related to https://github.com/yiisoft/event-dispatcher/issues/22

**Comment by armpogart** [comment]
Hmm... I don't have much experience in Java, but C++ doesn't have such thing for sure without explicit `friend` class declaration (that's obvious as there's no runtime in C++ and the compiler can't do such magic) and C# that works with runtime similar to JVM also doesn't have a such thing. That's why I thought that it is not a good OO pattern.

Anyways the point is that we don't have any autocomplete there. Is there any specific reason why the `Container::set` method is not public API?

**Comment by samdark** [comment]
The idea is the same as with event dispatcher. To disallow setting container runtime and allow it only at configuration time.

**Comment by samdark** [comment]
Decided to keep it as is for a while.
