### ISSUE TITLE
Rename `DelayedServiceProvider` to `DeferredServiceProvider`

### ISSUE THREAD

**Issue by SilverFire** [yiisoft/di#15]
Actually, the services get registered with no delay when they are requested. I think renaming to `DeferredServiceProvider` is more correct

**Comment by SilverFire** [comment]
@prowwid

**Comment by samdark** [comment]
Agree. Renaming it makes sense.

**Comment by prowwid** [comment]
Hello @samdark and @SilverFire 

Fixed in [PR 16](https://github.com/yiisoft/di/pull/16)

With best regards,
Dmitry
