### ISSUE TITLE
Simplify contributing

### ISSUE THREAD

**Issue by prowwid** [yiisoft/di#18]
Right now in TravisCI build you add PHP Codesniffer package and check sources for compatibility with PSR 2 but it does not reflect on the development environment and produce "WTF Effect" once you create PR as locally your tests pass and everything seems to be ok.

I suggest to do following:
- add PHP Codesniffer  to dev dependencies
- update readme with required steps to do before creating PR that include running 
- update `.travis.yml` to not require `quizlabs/php_codesniffer`

Another thing I noticed in `.travis.yml`  is condition `if [ $TRAVIS_PHP_VERSION = '5.6' ];` but matrix include only 7.1 and 7.2. Maybe this condition should be removed?

**Comment by samdark** [comment]
Good suggestions. Thanks!
