### ISSUE TITLE
Ability to mark service as bootstrap

### ISSUE THREAD

**Issue by samdark** [yiisoft/di#190]
In case service is marked as "bootstrap" it is executed right after container is created. That would allow us to do bootstrapping.

Will solve https://github.com/yiisoft/app/pull/76

**Comment by BoShurik** [comment]
It can be solved with tags on an application layer. After creating container get all services tagged with `app.bootstrap` and execute them

**Comment by samdark** [comment]
It's likely not a great idea since bootstrapping isn't reponsibility of the container itself.
