### ISSUE TITLE
Move benchmark to another package

### ISSUE THREAD

**Issue by vjik** [yiisoft/di#223]
phpbench use PSR container only first version: https://github.com/phpbench/container/blob/def10824b6009d31028fa8dc9f73f4b26b234a67/composer.json#L13

This prevents the use of the second version of `psr/container` in DI.

**Comment by samdark** [comment]
Let's try pull-requesting there first.

**Comment by samdark** [comment]
The pull requset was merged so I guess moving benchmark is no longer needed.
