### ISSUE TITLE
Incorrect exception on trying to get object with undefined exception

### ISSUE THREAD

**Issue by vjik** [yiisoft/di#228]
Test https://github.com/yiisoft/di/blob/2cc9f803ece970bbbb5d8ccf740c3312e7580d1b/tests/Unit/ContainerTest.php#L570 :

```php
$container = new Container(
	[
		'car' => Car::class,
	]
);

$this->expectException(NotFoundException::class);
$container->get('car');
```

Should throws `NotInstantiableException` instead of `NotFoundException`.

**Comment by samdark** [comment]
Seems to contradict PSR:

![photo_2021-11-20_00-56-08](https://user-images.githubusercontent.com/47294/142698064-d843f1e5-4943-44a6-81ea-be00dbf6435a.jpg)
