### ISSUE TITLE
Provide `ServiceLocatorTrait`

### ISSUE THREAD

**Issue by klimov-paul** [yiisoft/di#24]
According to the [PSR recommendations](https://www.php-fig.org/psr/psr-11/#13-recommended-usage) instance of `Psr\Container\ContainerInterface` should be used as 'Service Locator'. At its present state current `yii\di\Container` behaves exacly like a 'service locator' for me instead of DI container.

Obviously accepting PSR-11 demands old `yii\di\ServiceLocator` to match `Psr\Container\ContainerInterface`. I suggets we may implement `ServiceLocatorTrait` inside this package providing general implementation for it to be used back at the core.

**Comment by samdark** [comment]
I'd keep it away from the package. It's better to implement it in the framework if we really need it.
