### ISSUE TITLE
CircularReferenceException will be triggered in the same process

### ISSUE THREAD

**Issue by ChisWill** [yiisoft/di#246]
In Swoole environment, multiple requests work in the same process, so the CircularReferenceException probably happend.
```php
 if (isset($this->building[$id])) {
      // other code
 }
```
In the above code at the Yiisoft\Di\Container.php:303, one request is building and the other request is coming to build in the same time , so the if condition`if ($this->building[$id])` will be true.

**Comment by yiiliveext** [comment]
Does this bug appear after the last container update?

**Comment by ChisWill** [comment]
> Does this bug appear after the last container update?

Yes，it always exists.
Don't you think we shouldn't save status in object properties like `$this->building[$id] = 1;`?
In Swoole Coroutine environment, it will be multiple request execute in the same process, so they will be read the same status in the same time.

**Comment by yiiliveext** [comment]
> > Does this bug appear after the last container update?
> 
> Yes，it always exists.
> Don't you think we shouldn't save status in the singleton property like `$this->building[$id] = 1;`?
> In Swoole Coroutine environment, it will be multiple request execute in the same process, so they will be read the same status in the same time.

Do you use Yii3 with Swool? Can you give me an example of a configuration to start an application in the Swool Coroutine environment?

**Comment by ChisWill** [comment]
Yes.
My swoole version is 4.6.7 and set `swoole.enable_coroutine = on`
Here is index.php:
```php
<?php

declare(strict_types=1);

use Swoole\Http\Request;
use Swoole\Http\Response;
use Test\Support\Bird;
use Yiisoft\Di\Container;

require(dirname(__DIR__, 1) . '/vendor/autoload.php');

$server = new \Swoole\Http\Server('0.0.0.0', 9501, SWOOLE_PROCESS, SWOOLE_SOCK_TCP);
$server->set([
    'worker_num' => 1
]);

\Swoole\Coroutine::set([
    'hook_flags' => SWOOLE_HOOK_ALL
]);

$container = new Container();

$server->on(\Swoole\Constant::EVENT_REQUEST, function (Request $request, Response $response) use ($container) {
    try {
        $container->get(Bird::class);
        $response->end('hi');
    } catch (Throwable $t) {
        $response->end($t->getMessage());
    }
});

$server->start();
```
Here is Bird.php:
```php
<?php

declare(strict_types=1);

namespace Test\Support;

final class Bird
{
    public function __construct()
    {
        sleep(3);
    }
}
```
Run `php public/index.php` inside terminal and open 'http://localhost:9501' in two browser.

**Comment by yiiliveext** [comment]
Thanks. I'll play around with this on the weekend.
