### ISSUE TITLE
Idea how to reproduce Yii 2.0 container behavior

### ISSUE THREAD

**Issue by hiqsol** [yiisoft/di#25]
Explaining short and rough but I hope you'll catch the idea.

`\yii\di\Container` class could be extended with `$isSingleton` property (better name is welcome).
When isSingleton=true then container will work as is in this implementation and return same instance for same ID.
When isSingleton=false then container will work as factory and create new instance every time for same ID.

Then it is possible to create singleton container having non-singleton container as its parent.
So former `definitions` config goes to non-singleton container and `singletons` config goes to singleton container. Then this singleton container can be used in `Yii::createObject` function to reproduce Yii 2.0 behavior: it will return singleton when found and create new object according to non-singleton definition otherwise.

**Comment by samdark** [comment]
Nope. Won't be enough as for factory it's crucial to be able to initialize objects on calling `get()`.

**Comment by hiqsol** [comment]
Sorry. I didn't `get()` you ;)
Could you please explain a bit.

**Comment by samdark** [comment]
There are parameters for the instance to be created passed in runtime: https://github.com/yiisoft/yii2/blob/master/framework/BaseYii.php#L349

But there's no way to pass params in container: https://github.com/yiisoft/di/blob/master/src/Container.php#L100

That's because https://github.com/yiisoft/di/issues/22#issuecomment-369869387

**Comment by hiqsol** [comment]
There are several options to pass params:

1. second parameter for `get()`, PSR doesn't prohibit it.
2. separate function to create object with params `build()` or `create()`
3. passing options in first parameter:
3a. as array:
```php
$obj = $container->get([
    '__class' => \my\service::class,
    '__constructor()' => [],
    'prop1'  => 'v1',
]);
```
3b. as object (please see https://github.com/container-interop/container-interop/issues/6#issuecomment-33132151)
```php
$obj = $container->get(new ContainerRequest([
    '__class' => \my\service::class,
    '__constructor()' => [],
    'prop1'  => 'v1',
]));
```
or
```php
$obj = $container->get(new ContainerRequest(\my\service::class, [
    '__constructor()' => [],
    'prop1'  => 'v1',
]));
```

What I want to say that ideas and implementation in this repository is already good enough for DI container.
But this code could be reused to get more.
The code could be refactored as generic object factory and `Container` on top of it.

**Comment by samdark** [comment]
PSR doesn't prohibit it, but it also states that container should not be used as service locator (that's what you do when you call `get()` explicitly).

**Comment by hiqsol** [comment]
Ok. My idea is to let the `Container` be as clean and pure as you prefer.
But let object creating code be reused in the way we got used to in yii 2.0

**Comment by samdark** [comment]
> But let object creating code be reused in the way we got used to in yii 2.0

Means allowing direct usage of container as service locator?

**Comment by hiqsol** [comment]
> Means allowing direct usage of container as service locator?

Yes. And even as factory. Why not?

Compare:

```php
class Foo {
    public function __construct(BarFactory $factory)
    {
        $bar = $factory->create(['some' => 'config']);
    }
}
```

```php
class Foo {
    /// GenericFactory is something sharing code with Container
    
    public function __construct(GenericFactory $factory)
    {
        $bar = $factory->create([
            '__class' => Bar::class,
            'some' => 'config',
        ]);
    }
}
```

**Comment by samdark** [comment]
https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-11-container.md#13-recommended-usage

**Comment by samdark** [comment]
Aha. This variant makes sense. How would you implement it?

**Comment by hiqsol** [comment]
Everything concerning generic object creation from config could be moved to class named like GenericFactory. Actually it's going to be very same to current `Container` with only difference - flag `sameEveryTime` (better names are welcome) telling if we want new object or the same every time.

Class hierarchy like this:

- GenericFactory
    - Container (sameEveryTime = true)
    - Factory (sameEveryTime = false)

Factory config can be put into the Container config like this:

```php
$container = new \yii\di\Container([
    EngineInterface::class => EngineMarkOne::class,
    \yii\di\Container::class => function ($container) {
	return $container;
    },
    \yii\di\Factory::class => [
	/// I would add Reference::to() - looks nice :)
	'parent' => \yii\di\Reference::to(\yii\di\Container::class),
	'definitions' => [
	    \my\widget::class => [
		'some' => 'config',
	    ],
	],
    ],
]);
```

In this configuration GenericFactory will work almost the same as yii 2.0 container but will look for non-singletons definitions first and then singletons.

**Comment by samdark** [comment]
With this inheritance tree how would you prevent Container having `$options` available in `get()` method?

**Comment by hiqsol** [comment]
GenericFactory should have `create` or `build` method with params and `get` without params.

**Comment by hiqsol** [comment]
Also please consider 3b option mentioned earlier.

**Comment by hiqsol** [comment]
I can make PR on weekend. We'll see how it goes.

**Comment by samdark** [comment]
OK

**Comment by SamMousa** [comment]
I do not think we should have a factory that extends our container or depends on it.
Instead we should implement a factory that:
- Uses `DependencyResolverInterface` for dependency resolution.
- Uses any PSR11 container to get those dependencies if possible.
- Falls back to creating the dependencies itself if the container doesn't have all definitions.

This is a recursive process where we try to get a (nested) dependency from the container first, but if that fails we try to instantiate it.

This factory is not PSR11 compliant so we should not implement that interface. This also allows us to change the signature however we want and use it in core.
If developers than want to use another PSR-11 implementation we just use that and our factory still works.

Only *downside* is that `yii/core` will have a hard requirement on `yii/di`, but since this library is small I don't see that as an issue.

**Comment by samdark** [comment]
OK. How about having the factory as part of the core then?

**Comment by SamMousa** [comment]
I'm working on it in DI for now, we'll see where we put it:blush:
