### ISSUE TITLE
Suggestion of small optimization for container methods (get, has)

### ISSUE THREAD

**Issue by k-samuel** [yiisoft/di#265]
Hi. 

Made some experiments with profiling and container performance tests. 

Found a couple of places where code can be optimized without breaking backward compatibility. 

- Removed overhead for search in the list of instantiated objects (_isset_ faster then _array_key_exists_)
- Removed overhead for determining the presence of a “tag@“ in the requested identifier (string operations and function calls in get method has hight cost)
- Added tests for get method and multiple get request for same $id 

The main difficulties, assumptions and what problems are not solved. 

Now performance tests checks creation of the container itself, there are no tests for its use (I assume that get calls should prevail + repeat). 
The current Container method testing bench collects dependencies in the form of Yiisoft\Definitions\Reference  (another package structure), which imposes a significant overhead. (in fact, we are testing it most of the time). 
Not sure if this is the most common container use case. 

Test profiles are dominated by the overhead of Yiisoft\Definitions (object structures and methods of another package) 

Nevertheless, we managed to achieve some results, although they are not particularly noticeable in this cut.

Before and after tests: 

| TestName | Before | After
| ------------- | ---  | ---
| **\Yiisoft\Di\Tests\Benchmark\ContainerBench** |  |  |
| benchConstruct |                                    887.331μs (±1.68%) |  Mo877.242μs (±1.83%)
| benchSequentialLookups # 0 |              1.873ms (±0.39%) | Mo1.811ms (±1.01%)
| benchSequentialLookups # 1 |               1.962ms (±1.58%) | Mo1.853ms (±1.31%)
| benchSequentialLookups # 2 |              1.965ms (±1.27%) | Mo1.893ms (±0.90%)
| benchRandomLookups # 0 |                  1.878ms (±1.39%) | Mo1.799ms (±0.68%)
| benchRandomLookups # 1 |                   1.943ms (±0.69%) | Mo1.850ms (±1.42%)
| benchRandomLookups # 2 |                   1.958ms (±0.91%) | Mo1.844ms (±0.91%)
| benchRandomLookupsComposite # 0 |  5.561ms (±1.93%) | Mo4.831ms (±0.75%)
| benchRandomLookupsComposite # 1 |  5.568ms (±0.83%) | Mo4.870ms (±0.59%)
| benchRandomLookupsComposite # 2 |  5.652ms (±1.00%) | Mo4.859ms (±0.93%)
| **\Yiisoft\Di\Tests\Benchmark\ContainerMethodHasBench** |  | 
| benchHasPredefinedExisting ✔️  |                542.277μs (±0.79%)  | **373.403μs** (±1.18%)
| benchHasPredefinedExistingMultiple ✔️ |   2.715ms (±1.24%) | **1.894ms** (±1.72%)
| benchGetPredefinedExisting |                 178.388μs (±0.44%) | 174.109μs (±1.53%)
| benchGetPredefinedExistingMultiple |    841.079μs (±1.15%) | 850.102μs (±1.72%)
| benchUndefinedExisting ✔️ |                        513.313μs (±1.64%) | **367.542μs** (±1.16%)
| benchUndefinedNonexistent ✔️ |                 M1.059ms (±0.65%) | **894.880μs** (±0.54%)

The solution with the tag is more like a hack and of course it worsens the readability of the code, on the other hand it improves the performance.
Most likely, dependency tagging is not the most common case, it may be worth implementing it differently. At the moment, a non-priority feature affects the entire runtime for each dependency search. 

Please check draft of PR in my repo: [https://github.com/k-samuel/di/pull/1](https://github.com/k-samuel/di/pull/1)

| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP version      | 
| Operating system |

**Comment by k-samuel** [comment]
An alternative is to add the configuration option to disable the feature with dependency tagging

**Comment by k-samuel** [comment]
Еще я обратил внимание, что наличие тэга в конфигурации определяется при помощи strpos «@tag», как вариант можно помечать тэги/алисы символом ‘@‘, тогда определение наличия такой конструкции в строке будет намного дешевле` $string[0] === ‘@‘`

I also noticed that the presence of a tag in the configuration is determined using strpos "@tag", alternatively, you can mark tags / alice with the symbol ‘@‘ then determining the presence of such construction in a string will be much cheaper `$string [0] === ‘@‘`

**Comment by vjik** [comment]
@k-samuel On which version of PHP were these benchmarks done?

**Comment by k-samuel** [comment]
> @k-samuel On which version of PHP were these benchmarks done?

7.4
