### ISSUE TITLE
Ability to store anything as dependency, not only objects

### ISSUE THREAD

**Issue by samdark** [yiisoft/di#29]
It could be useful to be able to store anything as the dependency: a scalar, an array, a string etc.

**Comment by cebe** [comment]
symfony container uses parameters for this, to not confuse actual class definitions with other values. https://symfony.com/doc/current/service_container/parameters.html

**Comment by hiqsol** [comment]
Getting those data will require explicit use of container.
I propose to put it into app params and get app object with constructor injection.

**Comment by samdark** [comment]
Sounds good. What would be the syntax?

**Comment by hiqsol** [comment]
That's how I'm already doing in my proposal.

Params are defined in params config:
https://github.com/hiqsol/core/blob/master/src/config/params.php
https://github.com/hiqsol/web/blob/master/src/config/params.php

And used in config like this:
https://github.com/hiqsol/core/blob/master/src/config/common.php

Note use of params in definition of 'app'.

Also params could be used with DI like this:

```php
class My
{
    public function __construct (\yii\base\Application $app)
    {
        $this->app = $app;
    }

    public function doSomething()
    {
         $option = $this->app->params['my.option'];
    }
}
```

But better use it like I use it directly in configs, see https://github.com/hiqsol/core/blob/master/src/config/common.php#L26
For us it is usually enough, we try not to use params in code, mostly in configs.

Also please see good example of use of params here:
https://github.com/hiqdev/yii2-hiart/blob/master/src/config/common.php
With new DI this example will look even simpler: 
https://github.com/hiqdev/yii2-hiart/blob/3.0/src/config/common.php

**Comment by SamMousa** [comment]
We can support this by wrapping these values in `ValueDependency`.
No additional coding needed, syntax could be improved though.
```php
$container->set('coolValue', new ValueDependency('valueX'));
```
This uses the same code path as `Reference::to('otherService')`, with the exception that we don't check for circular references for things that are not references...

**Comment by samdark** [comment]
Fine idea but, indeed, syntax could be improved.
