### ISSUE TITLE
New in initializers in PHP 8.1

### ISSUE THREAD

**Issue by mj4444ru** [yiisoft/di#291]
```php
class Color {}

class Blue extends Color {}

class Car
{
    public function __construct(public readonly Color $color = new Blue())
    {
    }
}

$config = ContainerConfig::create()->withDefinitions([]);
$container = new Container($config);
```

I am expecting the next 2 lines of code to return the result.

```php
var_dump(new Car());
var_dump($container->get(Car::class));
```

But I get a different result.

```php
object(App\Controller\Car)
  public readonly App\Controller\Color 'color' => object(App\Controller\Blue)
object(App\Controller\Car)
  public readonly App\Controller\Color 'color' => object(App\Controller\Color)
```

It seems to me that the result in this case should be the same.
An exception can only be an explicitly defined definition for an expected class.

| Q                | A
| ---------------- | ---
| Version          | 1.0.0
| PHP version      | 8.1

**Comment by BoShurik** [comment]
For 
```
public function __construct(LoggerInterface $logger = new NullLogger())
```
you expect `NullLogger` instead of configured `LoggerInterface` instance?

**Comment by samdark** [comment]
@BoShurik his case is when there's no `LoggerInterface` configured in the container. In this case falling back to `NullLogger` seems to be correct action.

**Comment by BoShurik** [comment]
From the container POV `LoggerInterface` and `Color` - just a service ids, but `Color` is instantiable so can be fetched from container without definition. 
What about `public function __construct(public readonly ?Color $color = null))`? Should container create `Color` instance?

**Comment by samdark** [comment]
Default should be used in this case which is `null`.

**Comment by mj4444ru** [comment]
If we want to use something instead of the default, we have to customize the container.
I believe that the default takes precedence over the value of the same type in the container itself.
At the same time, it is naturally the highest priority for determining the configuration of the container.

**Comment by mj4444ru** [comment]
The same goes for factory behavior.
https://github.com/yiisoft/factory/issues/157

**Comment by vjik** [comment]
> If we want to use something instead of the default, we have to customize the container. I believe that the default takes precedence over the value of the same type in the container itself. At the same time, it is naturally the highest priority for determining the configuration of the container.

Container resolve dependencies and if container can resolve dependency, he does it, and if he doesn't, then used default value. So object is from the container has priority over default value. I think this is correct.

Added support objects as default values here: https://github.com/yiisoft/definitions/pull/31
