### ISSUE TITLE
Automatically resolve class-ids with autloading

### ISSUE THREAD

**Issue by samdark** [yiisoft/di#30]
It could be useful for mocking in tests to automatically resolve `$container->get(Foo\Bar::class)` to an instance of that class using PHP autoloader currently registered.

**Comment by SamMousa** [comment]
This is not PSR-11 compliant; unless we return true for `$container->get(Foo\Bar::class)` for any class that can be autoloaded.

This functionality could easily be implemented by a lightweight container wrapper, that consumes a PSR11 container and catches the appropriate exceptions and manually instantiates those classes (with the help of the PSR11 container and dependency resolver).

**Comment by samdark** [comment]
Indeed.
