### ISSUE TITLE
Check tag services array in `Container::setTags()` on empty

### ISSUE THREAD

**Issue by vjik** [yiisoft/di#312]
Now we can add tag with empty array and `$container->has()` returns true. It's wrong.

**Comment by xepozz** [comment]
I think it's totally okay to have an empty tags.
First of all, we shouldn't put sticks in the wheels. Making a developer remove a line or start a debugging research do it.
An empty tag may be computed during some operations from config (removing keys or values).
There are nothing bad if sometime tag can be empty. It's ok to have it. You may provide a point of the expansion of your library. 
Also tagged definitions are `iterable`. Empty tag is also iterable.

**Comment by vjik** [comment]
> I think it's totally okay to have an empty tags. First of all, we shouldn't put sticks in the wheels. Making a developer remove a line or start a debugging research do it. An empty tag may be computed during some operations from config (removing keys or values). There are nothing bad if sometime tag can be empty. It's ok to have it. You may provide a point of the expansion of your library. Also tagged definitions are `iterable`. Empty tag is also iterable.

Should  `$container->has()` returns `true` on empty tag?

**Comment by xepozz** [comment]
For sure

**Comment by vjik** [comment]
Ok, agree
