### ISSUE TITLE
Rename `Container::configure()` to `Container::setMultiple()`

### ISSUE THREAD

**Issue by klimov-paul** [yiisoft/di#5]
I suggest renamiing of `Container::configure()` into `Container::setMultiple()`.
The reasons are:

- "configure" is too generic word
- `setMultiple()` is more PSR style (used at [psr/simplecache](https://github.com/php-fig/simple-cache/blob/master/src/CacheInterface.php#L83))

**Comment by samdark** [comment]
It looks less "cool" but, indeed, described what happens under the hood better.

@SilverFire, @cebe, @dynasource  what do you think?

**Comment by samdark** [comment]
@yiisoft/reviewers ?

**Comment by schmunk42** [comment]
I find `setMultiple()` much clearer.

**Comment by samdark** [comment]
Let it be then.
