### ISSUE TITLE
Apply callable class fix from Yii 2.0

### ISSUE THREAD

**Issue by samdark** [yiisoft/di#50]
See https://github.com/yiisoft/yii2/pull/16528 and then https://github.com/yiisoft/yii2/commit/1f709e71336dda51a13f2c9f26f4361d515b0c00

**Comment by SamMousa** [comment]
This is fixed by #57, specifically this line: https://github.com/yiisoft/di/blob/99d3005ffdfddde5cc527c32e9a286324f2eda7e/src/resolvers/ClassNameResolver.php#L68
