### ISSUE TITLE
Set up PHPBench

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/di#58]
@samdark this one is for you.

https://phpbench.readthedocs.io/en/latest/extensions/reports.html#configuration

Note that my PR has some basic benchmarks included.
When you set up travis it's easiest (in my experience) to use the composer scripts.
```
composer test #run all tests
composer bench #run all benchmarks
```

**Comment by samdark** [comment]
@cebe we have ElasticSearch instance for yiiframework.com. Do you think we can set up PHPBench at the same server using a sub-domain such as phpbench.yiiframework.com?

**Comment by cebe** [comment]
how is this related to elasticsearch? We could set up something, but I did not get what exactly to set up from the little context given here :)

**Comment by samdark** [comment]
@cebe this thing: https://github.com/phpbench/phpbench-reports
