### ISSUE TITLE
Factories

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/di#59]
One goal of a factory is to create a concrete implementation of an interface without knowing anything about the implementation.

For example, an application might want to create PSR7 responses without knowing anything about the underlying implementation in use.
This means that the create method of a factory should look roughly like this:
```php
public function create($a, $b): SomeInterface;
```

The factory abstracts the how; we do not know if it passes `$a` and `$b` to a constructor, or uses setters, or even public properties.
The current implementation is not really a factory, but a wrapper around PHP `__construct`. All it does is provide a different syntax, while still binding to the concrete implementation.

Alternatively, the goal of a factory might be to hide the fact that the class it's creating has dependencies that we want to automatically inject.
This is the following pattern:
```php

public function __construct(DepA $dependencyA) {
    $concretes = [];
    for ($i = 1; $i < 10; $i++) {
        $concretes[] = new SomeClass($dependencyA);
    }

}

```
Here our code is depending on a concrete implementation that it needs to instantiate.
A factory would allow us to clarify that our class doesn't directly need `DepA`, instead it just happens to use a class that needs it.
In this case, since we know the concrete class, it makes sense for the factory to:
- Have a `create` function that supports all constructor parameters of the underlying class.
- Have a `createX` function for all static constructors.

Regardless of which of these 2 cases is used, factories should only create instances of a single class or interface.

In Yii we have the convention to use array configuration and it might make sense to use similar configuration for the factory as we do for the DI container:
```php
$factoryConfig = [
    Car::class => [
        '__construct()' => [
            EngineInterface::class => EngineMarkTwo::class
        ]
];
```

While this allows us to create one big factory for every configured (and even unconfigured?) class this isn't really the type of factory we should be injecting.

Instead we could create a `FactoryFactory` that, on demand, creates a factory for a class.
This could be done fully automated but this will require a lot of magic; either by creating classes on the fly using autoloading or by looking at variable names and deciding what to inject.

```php
public function __construct(FactoryInterface $carFactory) {

}

```

The downside is that the interface will always be incomplete; it can't include multiple constructors and it can't provide the correct constructor arguments.

For the Yii core, there's just a few classes that we construct in this way, and in my opinion we should implement specific factories for those instead `ActiveRecordFactory`.
For all subclasses of `ActiveRecord` we know how to configure them and we can easily provide defaults. Note that currently we already have an AR specific factory in the form of: `BaseActiveRecord::instantiate()`, which is a factory.

@hiqsol I'm pinging you since you laid the groundwork for this library and I'd love your thoughts the reasoning behind the choices you made for the current implementation.

I'd like to ask everyone to state what their requirements / use cases are for the factory as part of a DI library.

**Comment by hiqsol** [comment]
@SamMousa I just wanted several things:

- have it simple
- have all 2.0 capabilities
- do it quick

I think an automated factory creating factories with interfaces is a complex idea :) Also, I've always avoided even factory factories. Sometimes simpler solutions are harder to find :)

What I see very rational in your idea is avoid making code dependent of concrete DI implementation:

```php
class MyCar {
    public function __construct(\yii\di\Factory $engineFactory);
}
```

with implicit factory:

```php
class MyCar {
    public function __construct(EngineFactoryInterface $engineFactory);
}
```

But automatic `EngineFactoryInterface` creation is too much for me :)

I think it is easier and more practical to have `EngineFactoryInterface` actually defined and allow DI create its instances which will use `yii\di\Factory` inside.
With config like this:

```php
$config = [
    EngineFactoryInterface::class => function ($factory) {
        return $factory->createFactoryFor(EngineFactoryInterface::class);
    },
];
```

`createFactoryFor()` will create class implementing needed interface and its instance that uses `$factory` to create objects.

Also I think in some places in the framework explicit factories are really needed.

**Comment by SamMousa** [comment]
Agree with most if what you said.
Your last example looks clean, I agree that defining factories as services in DI makes sense. However, that automated factory creation will not support additional constructors.

Also, if we are manually defining the interface:
```php
interface EngineFactoryInterface {
    public function create(int $cilinders = 8);
}
```
Then we can just as well manually create the actual factory:
```php
class EngineFactory {
    public function create(int $cilinders = 8): EngineInterface 
    {
        $result = new Engine();
        $result->setCilinderCount(8);
        return $result;
    }
    public function alternativeCreate(): EngineInterface
    {
        return Engine::createWithCilinders(8);
    }
}
```

In many scenarios it might even make sense to not define the interface (in cases where you're not likely to replace the factory implementation anyway).

**Comment by samdark** [comment]
1. In Yii 2.0 Container was both factory and service repository at the same time. It was determined by "singleton" marker and potentially was error prone.
2. I've decided to separate container as service repository from container as factory. Both should resolve dependencies. Factory should create new instances while container should not. Factory should be able to resolve dependencies from container.

**Comment by SamMousa** [comment]
OK that is clear, and we can implement that. 

How do you envisage usage of this factory in the core?
I've looked at the usages of `Yii::createObject()` and it used mostly for allowing array configuration.
That is essentially the service locator pattern.

In some cases like widgets it is used as a factory.

Would you be open to have specific factories?
Like having a widget factory that is injected into the view? Widgets are all used in the same way so the factory would be simple and clean.
I think it's similar for some other use cases.

The configuration part could be handled by DI since it is not really the factory pattern.

Would you consider an syntax where we wrap properties like log targets in an object similar to `Reference::to()`?

**Comment by samdark** [comment]
"Widget" factory isn't too specific so I'm fine about it. In general, as long as we don't go extreme like "each class should have a specific factory", it's all good.

> Would you consider an syntax where we wrap properties like log targets in an object similar to Reference::to()?

An example?

**Comment by SamMousa** [comment]
```php
'log' => [
    'targets' => [
         'target1' => Reference::to('servicefromdi'),
'target2' => Reference::dynamic([
'__class' => X::class
]
    ]
]
```

Short example, phone not the best medium:smile:
