### ISSUE TITLE
Right way to create object

### ISSUE THREAD

**Issue by FabrizioCaldarelli** [yiisoft/di#66]
I need that object init() method is called, because it implements Initiable.

But I have found that init() method is called only if object is created with DI.

So I can create my \yii\web\UrlManager object in this way;

`
$manager = new UrlManager( $this->app, new UrlNormalizer() );
`

but init() method is not called.

To be sure that init() method is called, I have to write:

`
$manager = $this->app->createObject(['__class' => UrlManager::class], ['app' => $this->app, 'normalizer' => new UrlNormalizer() );
`

but this way to create object is very ugly and little intuitive.

Is there a more elegant way to create an object and ensure that init() method is called ?

If there are not other options to create an object, maybe it would be better that BaseObject had an its constructor that checked if child class implemented Initiable interface and finally call child init() method.

**Comment by samdark** [comment]
I'd remove initable support overall since it's Yii-specific and DI container isn't. We're keeping it only to be able to have something that works as 3.0 master for the time we're moving towards constructor-based initialization.

**Comment by hiqsol** [comment]
> I'd remove initable support overall since it's Yii-specific and DI container isn't. We're keeping it only to be able to have something that works as 3.0 master for the time we're moving towards constructor-based initialization.

Yes. This is my idea too.
The plan is: fix all tests (in all packages), fix example application and then refactor and refactor until we can remove Initiable.
