### ISSUE TITLE
Lazy services support

### ISSUE THREAD

**Issue by hiqsol** [yiisoft/di#74]
Discussion was started in: https://github.com/yiisoft/di/pull/57#issuecomment-473340210

> I'd not want the proxy manager as a hard dependency of DI, but I definitely would like to support it

It could be suggested in `composer.json` and then something like `if class_exists` then it works else silently works without it.

Syntax could be something like this:

```php
    \my\ServiceInterface::class => [
        '__class' => \my\Service::class,
        '__lazy' => true,
    ],
```

**Comment by rob006** [comment]
> It could be suggested in `composer.json` and then something like `if class_exists` then it works else silently works without it.

You will not be able to define constraints in such case - `class_exists` may return `true`, but you may get different class than you expected.

**Comment by hiqsol** [comment]
> `class_exists` may return `true`

Sorry, I didn't get you.
I've meant to use `if class_exists(`\ProxyManager\Factory\LazyLoadingValueHolderFactory::class)` to detect if ProxyManager package is installed.

**Comment by rob006** [comment]
I mean that `class_exists(\ProxyManager\Factory\LazyLoadingValueHolderFactory::class)` tells you that package is probably installed, but does not tel you nothing about version of this package. And `LazyLoadingValueHolderFactory` in v2.0.0 may have different signature and behavior than in v3.0.0.

**Comment by samdark** [comment]
How about making every dependency lazy by default?

**Comment by rob006** [comment]
@samdark I don't think that this is worth the additional overhead. I'm not sure if it is even possible (final classes may be a problem).
