### ISSUE TITLE
Fall back to autoloader when class is not in container

### ISSUE THREAD

**Issue by samdark** [yiisoft/di#88]
Currently there's a need to declare everything that is repetitive if we need to set a single class without an interface into container:

```php
\App\ConsoleCommand\CreateUser::class => \App\ConsoleCommand\CreateUser::class,
```

In such cases we can try to fall back to class autoloading.

**Comment by rustamwin** [comment]
using `aliases`?

**Comment by samdark** [comment]
No.

**Comment by rugabarbo** [comment]
@samdark it seems already implemented: https://github.com/yiisoft/di/blob/7dd3ce1b33e5ac28a7782285671dffba1b2488e1/tests/Unit/ContainerTest.php#L64-L69

**Comment by samdark** [comment]
Does that work for sub-dependencies?

**Comment by rugabarbo** [comment]
There is the incomplete test about it: 
https://github.com/yiisoft/di/blob/7dd3ce1b33e5ac28a7782285671dffba1b2488e1/tests/Unit/ContainerTest.php#L42-L51

The test passes successfully in this form:
```php
    public function testOptionalClassDependency(): void
    {
        $container = new Container();
        $container->set(A::class, A::class);

        $a = $container->get(A::class);
        $this->assertInstanceOf(B::class, $a->b);
    }
```

Console output:
```bash
$ ./vendor/bin/phpunit --filter=testOptionalClassDependency
PHPUnit 7.5.16 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.2.22-1+ubuntu16.04.1+deb.sury.org+1 with Xdebug 2.7.2
Configuration: /tmp-for-test/yii-dev/dev/di/phpunit.xml.dist

.                                                                   1 / 1 (100%)

Time: 79 ms, Memory: 4.00 MB

OK (1 test, 1 assertion)
```

Therefore, it is not clear what exactly needs to be changed.

**Comment by rugabarbo** [comment]
It seems like we can just adjust the tests and close this task. Do you agree?

**Comment by samdark** [comment]
Yes. I've re-checked it and it works.

**Comment by rugabarbo** [comment]
@samdark, it seems that things are not so simple. I see that design solutions are needed here.

Now autoload is triggered by calling method `class_exists` here: https://github.com/yiisoft/di/blob/7dd3ce1b33e5ac28a7782285671dffba1b2488e1/src/Container.php#L128

If you add a new test to the test suite, then it passes:
```php
    public function testDependenciesWithoutDefinition(): void
    {
        $container = new Container();
        $a = $container->get(A::class);
        $this->assertInstanceOf(A::class, $a);
        $this->assertInstanceOf(B::class, $a->b);
    }
```

Thus, autoload is triggered for undeclared classes and their dependencies, **BUT** for consistency, method `Container::has()` should also return `true` for undeclared classes. Now it doesn't:
https://github.com/yiisoft/di/blob/7dd3ce1b33e5ac28a7782285671dffba1b2488e1/src/Container.php#L182-L191

Moreover, there is a test suite that relies on this behavior of `has()` method:
https://github.com/yiisoft/di/blob/7dd3ce1b33e5ac28a7782285671dffba1b2488e1/tests/Unit/ServiceProviderTest.php#L30-L41

So, it looks like the implementation of the container is now inconsistent. We should discuss this and make some decisions about how it should work.

**Comment by samdark** [comment]
has() should behave same as get() now. Could be achieved by triggering autoloading for class_exists() in case there's nothing directly registered in container.

**Comment by rugabarbo** [comment]
> has() should behave same as get() now. Could be achieved by triggering autoloading for class_exists() in case there's nothing directly registered in container.

But this approach can cause performance problems. What do you think about it?

**Comment by samdark** [comment]
Why should it cause performance problems?

**Comment by rugabarbo** [comment]
> Why should it cause performance problems?

Typically, method `Container::has()` is massively used to determine the availability of services in a project. When some services are unavailable, many misses occur. In our implementation each miss will cause autoload. For example, composer requires optimization of the second level in order to quickly work with misses: https://getcomposer.org/doc/articles/autoloader-optimization.md#trade-offs

> The only issue is it does not keep track of autoload misses (i.e. when it can not find a given class), so **those fallback to PSR-4 rules and can still result in slow filesystem checks**. To solve this issue two Level 2 optimization options exist, and you can decide to enable either if you have a lot of class_exists checks that are done for classes that do not exist in your project.

Calling method `isset()` is quick. But calling method `isset()` in combination with method `class_exists()`, it seems to me, can cause performance problems in typical configurations. You think we don’t need to worry about it now?

**Comment by rugabarbo** [comment]
@samdark I just created benchmarks for method `Container::has()`. 
See #90.

### Test N1

#### Method `Containter::has()` implementation (current):
```php
    public function has($id): bool
    {
        return isset($this->definitions[$id]);
    }
```
#### Bench results:
```bash
$ ./vendor/bin/phpbench run --filter=MethodHas
PhpBench 0.14.0 (@git_version@). Running benchmarks.
Using configuration file: /yii-dev/dev/di/phpbench.json

\Yiisoft\Di\Tests\Benchmark\ContainerMethodHasBench

    benchPredefinedExisting       I4 P0 	[μ Mo]/r: 0.070 0.070 (μs) 	[μSD μRSD]/r: 0.001μs 1.66%
    benchUndefinedExisting        R2 I3 P0 	[μ Mo]/r: 0.071 0.071 (μs) 	[μSD μRSD]/r: 0.001μs 1.38%
    benchUndefinedNonexistent     R3 I4 P0 	[μ Mo]/r: 0.069 0.068 (μs) 	[μSD μRSD]/r: 0.002μs 2.25%

3 subjects, 15 iterations, 3,000 revs, 0 rejects, 0 failures, 0 warnings
(best [mean mode] worst) = 0.068 [0.070 0.070] 0.072 (μs)
⅀T: 1.052μs μSD/r 0.001μs μRSD/r: 1.761%
```

### Test N2

#### Method `Containter::has()` implementation (proposed):
```php
    public function has($id): bool
    {
        return isset($this->definitions[$id]) || (is_string($id) && class_exists($id));
    }
```
#### Bench results:
```bash
$ ./vendor/bin/phpbench run --filter=MethodHas
PhpBench 0.14.0 (@git_version@). Running benchmarks.
Using configuration file: /yii-dev/dev/di/phpbench.json

\Yiisoft\Di\Tests\Benchmark\ContainerMethodHasBench

    benchPredefinedExisting       I4 P0 	[μ Mo]/r: 0.071 0.071 (μs) 	[μSD μRSD]/r: 0.001μs 1.65%
    benchUndefinedExisting        R2 I3 P0 	[μ Mo]/r: 0.361 0.364 (μs) 	[μSD μRSD]/r: 0.008μs 2.21%
    benchUndefinedNonexistent     R1 I2 P0 	[μ Mo]/r: 0.538 0.527 (μs) 	[μSD μRSD]/r: 0.016μs 2.93%

3 subjects, 15 iterations, 3,000 revs, 0 rejects, 0 failures, 0 warnings
(best [mean mode] worst) = 0.069 [0.323 0.321] 0.072 (μs)
⅀T: 4.846μs μSD/r 0.008μs μRSD/r: 2.261%
```

**Comment by samdark** [comment]
1. Was the tests conducted with composer [autoloader optimized](https://getcomposer.org/doc/articles/autoloader-optimization.md)?

**Comment by rugabarbo** [comment]
> 1. Were the tests conducted with composer [autoloader optimized](https://getcomposer.org/doc/articles/autoloader-optimization.md)?

Yes. I used: 
```bash
composer install --optimize-autoloader
```

> 2. Triggering autoload is, of course, slower but I think we can ignore it in this case because `has()` is rarely used by itself. Usually it's `get()`.

Ok, I also think that we can ignore this, because these are fractions of microseconds.

> 3. There's a usage that should be checked in Factory: https://github.com/yiisoft/factory/blob/master/src/Factory.php#L55

Ok, I'll check it too.

**Comment by terabytesoftw** [comment]
If it works perfectly, but my question is, by allowing to declare a class that does not exist in the container with the set method, and automatically pass all its dependencies to the constructor, it is not the same as using a service locator, basically we are doing a Yii::createObject().

**Comment by rugabarbo** [comment]
@samdark, mark the item completed in the roadmap: https://github.com/yiisoft/docs/blob/master/003-roadmap.md

**Comment by samdark** [comment]
Done.

**Comment by nd4c** [comment]
Is the [Factory issue https://github.com/yiisoft/factory/issues/3](https://github.com/yiisoft/factory/issues/3) also closed?

**Comment by rugabarbo** [comment]
> Is the [Factory issue https://github.com/yiisoft/factory/issues/3](https://github.com/yiisoft/factory/issues/3) also closed?

No, because the future of package `factory` is unclear. Now class `Factory` is not used anywhere.
