### ISSUE TITLE
Number instead Numer in tests?

### ISSUE THREAD

**Issue by demonking** [yiisoft/di#91]
### What steps will reproduce the problem?
Clone Repository
Run tests

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP version      | 
| Operating system |

Shouldn't it be called getNumber? Or is there a reason for calling it getNumer?

./tests/Unit/ContainerTest.php:298:        $this->assertSame($number, $engine->getNumer());
./tests/Support/EngineMarkTwo.php:33:    public function getNumer(): int
./tests/Support/EngineMarkOne.php:33:    public function getNumer(): int
./tests/Support/EngineInterface.php:22:    public function getNumer(): int;

**Comment by rugabarbo** [comment]
This is mistake.
I'll fix this a bit later.

**Comment by demonking** [comment]
i close this one, have created a PR
